### ISSUE TITLE
Please update readme to include reason for staying on Slack instead of going to Gitter or some other platform.

### ISSUE THREAD

**Issue by aaronjensen** [reactiflux/volunteers#16]
The two issues listed on the readme are purely Slack issues. I reached out to Slack to see if they'd be willing to extend licenses to OSS communities for free and got "Thanks for the feedback." It's pretty clear they don't really care, so what makes Slack so great that we are willing to build tools around it rather than use something like Gitter (Which, admittedly, I've not used much, but it seems to be worth exploring). Maybe you all have explored it, maybe you've got awesome reasons for spending time and energy to keep us on Slack, either way it'd be helpful to see some reasoning for it before deciding whether or not we want to help out. Thanks!

**Comment by zackify** [comment]
The reason is because there are already thousands of us on slack. Someone
saying "Ok, let's move to x service" isn't going to get everyone to leave
slack. Slack has a nice interface and everyone I know is already on it.
Most people don't want to go sign up for something else. Although it is sad
that they won't help out OS projects, I think doing this has some benefits.
We will have all the messages data on our own server and can build any UI
we want to see the archives. Even if we switched to another service that
kept messages, I don't think there would be an easy way to have a
searchable interface for those not using the service.
